server:
  port: 32111
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://xxxxxx:3306/aku_trace?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: app
    password: xxxx#^!
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic: #动态数据源组件 https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter
      primary: master # 配置默认数据库
      datasource:
        master:
          url: jdbc:mysql://xxxxxxxxxxxxx:3306/aku_trace?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
          username: app
          password: xxxx#^!
        slave:
          url: jdbc:mysql://xxxxxxxxxxxxxxxxx:3306/aku_trace?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
          username: app
          password: xxxx#^!
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置
  cloud:
    nacos:
      discovery:
        server-addr:
        register-enabled: true
  # redis配置
  redis:
    #host: redis.al
    host: xxxxxx
    password: xxxxxxxxxxxxxxxx
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 500ms
        min-idle: 0


# 定时任务
al:
  job:
    executor:
      adminAddresses: xxxxxxxxxxxx
      port: 43259
      logpath: /data/logs/trace-service/jobhandler


log.level: INFO
trace-service:
  gitlabUsername: xxxxxx
  gitlabPassword: xxxxxx
  servicePath: /data/logs/trace-service/git
  tapdWorkspaceId: xxxxx
  applications:
    "calculation-service":
      #实际git上的最小目录下的项目名称,如果为空  说明没有子目录 这就是最小目录
      serviceName: xxxx
      # gitlab地址
      gitlabUrl: xxxx
      # 启动类
      mainClass: xxxx
    "trade-biz":
      serviceName: trade
      gitlabUrl: https://xxxxxxxxx.git
      mainClass: xxxxx.TradeApplication

